/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165 } from "./ERC165.ts";
export type { ERC721 } from "./ERC721.ts";
export type { IERC165 } from "./IERC165.ts";
export type { IERC721 } from "./IERC721.ts";
export type { IERC721Metadata } from "./IERC721Metadata.ts";
export type { IERC721Receiver } from "./IERC721Receiver.ts";
export type { NewNFT } from "./NewNFT.ts";
export type { NewNFTMarket } from "./NewNFTMarket.ts";
// export * as factories from "./factories/index.ts";
export type { ERC165__factory } from "./factories/ERC165__factory.ts";
export type { ERC721__factory } from "./factories/ERC721__factory.ts";
export type { IERC165__factory } from "./factories/IERC165__factory.ts";
export type { IERC721__factory } from "./factories/IERC721__factory.ts";
export type { IERC721Metadata__factory } from "./factories/IERC721Metadata__factory.ts";
export type { IERC721Receiver__factory } from "./factories/IERC721Receiver__factory.ts";
export type { NewNFT__factory } from "./factories/NewNFT__factory.ts";
export type { NewNFTMarket__factory } from "./factories/NewNFTMarket__factory.ts";
