/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165__factory } from "./ERC165__factory.ts";
export type { ERC721__factory } from "./ERC721__factory.ts";
export type { IERC165__factory } from "./IERC165__factory.ts";
export type { IERC721__factory } from "./IERC721__factory.ts";
export type { IERC721Metadata__factory } from "./IERC721Metadata__factory.ts";
export type { IERC721Receiver__factory } from "./IERC721Receiver__factory.ts";
export type { NewNFT__factory } from "./NewNFT__factory.ts";
export type { NewNFTMarket__factory } from "./NewNFTMarket__factory.ts";
